# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        maven: [ '3.8.5' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        maven-version: ${{ matrix.maven }}
    - name: Execute Tests
      run: mvn clean test -DsuiteXmlFile=testng.xml
    - name: Upload a Test Results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Backend Test Reports
        path: target
